Create NumPy Arrays
Create:
1D array
2D array
3D array

Practice:

import numpy as np

Concepts:

np.array()
Dimensions
Shape

In [65]:
import numpy as np
p=np.array([1,2,3])
print(p)

[1 2 3]


In [66]:
q=np.array([[1,8,6],[2,4,4]])
print(q)

[[1 8 6]
 [2 4 4]]


In [67]:
r=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [68]:
r.shape

(2, 2, 2)

In [69]:
q.ndim

2

In [70]:
p.size

3

Create Special Arrays

Create:

Zeros array
Ones array
Identity matrix
Random array

Concepts:

np.zeros()
np.ones()
np.eye()
np.random.rand()

In [71]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [73]:
import random
np.random.rand(4)

array([0.39676747, 0.53881673, 0.41919451, 0.6852195 ])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
arr=p[1:4]
print(arr)

[2 3]


In [76]:
f=q[-1,-2]
print(f)

4


In [77]:
k=r[:,1]
print(k)

[[3 4]
 [7 8]]


Array Reshaping

Convert:

1D → 2D
2D → 1D

Concepts:

reshape()
flatten()
ravel()

In [78]:
import numpy as np
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print("--- Using flatten() ---")
flat_arr = matrix.flatten()
flat_arr[0] = 99  
print("Flattened Array:", flat_arr)
print("Original Matrix (Unchanged):\n", matrix)

print("\n--- Using ravel() ---")
rav_arr = matrix.ravel()
rav_arr[0] = 99  
print("Raveled Array:", rav_arr)
print("Original Matrix (CHANGED!):\n", matrix)


--- Using flatten() ---
Flattened Array: [99  2  3  4  5  6]
Original Matrix (Unchanged):
 [[1 2 3]
 [4 5 6]]

--- Using ravel() ---
Raveled Array: [99  2  3  4  5  6]
Original Matrix (CHANGED!):
 [[99  2  3]
 [ 4  5  6]]


Mathematical Operations on Arrays

Perform:

Addition
Subtraction
Multiplication
Division
Power

Concepts:

Vectorized operations
Broadcasting basics
Find:

Mean
Median
Standard deviation
Min/Max
Sum

In [79]:
import numpy as np
a = np.array([12, 34, 22])
b = np.array([67, 87, 56])

c = (a + b)
d = (a - b)
e = (a * b)
f = (a / b)
g = (a ** 2)

print("Addition (c):\n", c)
print("\nSubtraction (d):\n", d)
print("\nMultiplication (e):\n", e)
print("\nDivision (f):\n", f)
print("\nPower of 2 (g):\n", g)
z=a.mean()
x=c.std()
print("mean is:",z)
print("std is:",x)

Addition (c):
 [ 79 121  78]

Subtraction (d):
 [-55 -53 -34]

Multiplication (e):
 [ 804 2958 1232]

Division (f):
 [0.17910448 0.3908046  0.39285714]

Power of 2 (g):
 [ 144 1156  484]
mean is: 22.666666666666668
std is: 20.038851153585515


Filtering Arrays

Extract:

Even numbers
Numbers > 50
Negative numbers

Concept:

Boolean masking

Example:

arr[arr > 50]

In [80]:
import numpy as np
arr = np.array([12, -7, 55, 34, -2, 88, 15, -40, 61])

print("Original Array:", arr)
print("-" * 40)

mask_gt50 = arr > 50
filtered_gt50 = arr[mask_gt50]
print("1. Numbers > 50:")
print("   Mask:   ", mask_gt50)
print("   Result: ", filtered_gt50)

mask_even = (arr % 2 == 0)
filtered_even = arr[mask_even]
print("\n2. Even Numbers:")
print("   Result: ", filtered_even)

mask_negative = arr < 0
filtered_negative = arr[mask_negative]
print("\n3. Negative Numbers:")
print("   Result: ", filtered_negative)

Original Array: [ 12  -7  55  34  -2  88  15 -40  61]
----------------------------------------
1. Numbers > 50:
   Mask:    [False False  True False False  True False False  True]
   Result:  [55 88 61]

2. Even Numbers:
   Result:  [ 12  34  -2  88 -40]

3. Negative Numbers:
   Result:  [ -7  -2 -40]


Stack and Split Arrays

Perform:

Horizontal stack
Vertical stack
Array splitting

Concepts:

np.hstack()
np.vstack()
np.split()

In [81]:
import numpy as np
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,2],
              [6,8]])
h_stacked = np.hstack((a,b))
v_stacked =np.vstack((a,b))
print("Horizontal Stack", h_stacked)
print("Vertical Stack",v_stacked)
print("-"*40)
large_array = np.array([10,30,48,56,69,78])
sub_array = np.split(large_array,3)
print("Original array:",large_array)
print("\nAfter splitting into 3 sections:")
for i, sub in enumerate(sub_array):
    print(f"Sub-array {i}: {sub}")

Horizontal Stack [[1 2 5 2]
 [3 4 6 8]]
Vertical Stack [[1 2]
 [3 4]
 [5 2]
 [6 8]]
----------------------------------------
Original array: [10 30 48 56 69 78]

After splitting into 3 sections:
Sub-array 0: [10 30]
Sub-array 1: [48 56]
Sub-array 2: [69 78]


Solve Linear Algebra Problems
Matrix multiplication
Determinant
Inverse matrix

Concepts:

np.dot()
np.linalg.det()
np.linalg.inv()

In [82]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
result=np.dot(A,B)
print(result)
det=np.linalg.det(A)
print(det)
inverse=np.linalg.inv(B)
print(inverse)

[[19 22]
 [43 50]]
-2.0000000000000004
[[-4.   3. ]
 [ 3.5 -2.5]]


Mini NumPy Data Analysis Project

Create random student marks dataset and perform:

Average marks
Highest marks
Lowest marks
Students scoring above 80
Subject-wise analysis

Concepts:

Real-world array operations
Aggregation
Filtering
Axis operations

In [83]:
import numpy as np

np.random.seed(1)

marks = np.random.randint(40, 101, size=(5, 3))

print("Student Marks Dataset:")
print(marks)

# Average
print("\nAverage Marks:")
print(np.mean(marks))

# Highest
print("\nHighest Marks:")
print(np.max(marks))

# Lowest
print("\nLowest Marks:")
print(np.min(marks))

# Above 80
print("\nMarks Above 80:")
print(marks[marks > 80])

# Subject-wise Average
print("\nSubject-wise Average:")
print(np.mean(marks, axis=0))

# Student-wise Average
print("\nStudent-wise Average:")
print(np.mean(marks, axis=1))

Student Marks Dataset:
[[ 77  83  52]
 [ 48  49  51]
 [ 45  55  40]
 [ 56  41  52]
 [ 47  85 100]]

Average Marks:
58.733333333333334

Highest Marks:
100

Lowest Marks:
40

Marks Above 80:
[ 83  85 100]

Subject-wise Average:
[54.6 62.6 59. ]

Student-wise Average:
[70.66666667 49.33333333 46.66666667 49.66666667 77.33333333]
